### ISSUE TITLE
Sidebar (Nav menu) Footer fails to position correctly in Grommet 1.0.1

### ISSUE THREAD

**Issue by ToddBarkalowHPE** [grommet/grommet#1080]
### Expected Behavior
When the nav sidebar menu is brought up, all items in the Footer should be at the bottom, as it is in all-but-IE browsers.

### Actual Behavior
See attached image to help assist (incorrect.png).  The SessionMenu is not in at the foot of the nav sidebar.  Example Footer code:

 <Footer pad={{horizontal: 'medium', vertical: 'small'}}>
          <SessionMenu dropAlign={{bottom: 'bottom'}} colorIndex="neutral-1-a" />
 </Footer>

### Steps to Reproduce
 1. Browse to https://hc380.grommet.io/ and show the nav sidebar menu

Note the human icon image is directly under Settings (for Grommet) when it should be at the bottom.
 
I attached image with correct / previous behavior (correct.png)

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Internet Explorer 11 (latest release)
* Operating System and version (desktop or mobile): Windows 10 desktop
![incorrect](https://cloud.githubusercontent.com/assets/22778995/20946543/5cb9bb6c-bbc8-11e6-9d5f-c69b087d14b0.png)
![correct](https://cloud.githubusercontent.com/assets/22778995/20946542/5cb8c8c4-bbc8-11e6-806c-9c242be4875b.png)

**Comment by ToddBarkalowHPE** [comment]
If it helps, our Platform GUI is behaving the same way before and after Grommet upgrade to 1.0.1.
![platform-incorrect](https://cloud.githubusercontent.com/assets/22778995/20947073/b5c137ba-bbca-11e6-8af9-3a462ecf3808.png)
![platform-correct](https://cloud.githubusercontent.com/assets/22778995/20947072/b5bdd746-bbca-11e6-9e0b-a411105fe13d.png)

**Comment by alansouzati** [comment]
Fixed in Grommet 1.1.0, please use fill option in Menu. See the 1.1.0 release notes for details.

https://github.com/grommet/grommet/releases/tag/v1.1.0

**Comment by ravindra1103** [comment]
I can still see a different behavior in between Chrome and Internet Explorer 11 
Examlpe: If i open http://ferret.grommet.io/dashboard this on Chrome user icon shows in the bottom left corner which is what we wanted but on IE it is not the case. Is ferret demo link using the latest grommet version

**Comment by alansouzati** [comment]
hi @ravindra1103 Ferret might still be outdated. are you still able to reproduce it with the latest grommet? can you create a codepen reproducing this?

**Comment by ravindra1103** [comment]
Hello @alansouzati  Thanks a lot for the response
I have created the codepen requested below. I am using the latest Grommet 1.1.0 version in the codepen settings.

https://cdnjs.cloudflare.com/ajax/libs/grommet/1.1.0/grommet.min.css
https://cdnjs.cloudflare.com/ajax/libs/grommet/1.1.0/grommet.min.js

 Please change to fullview and see the difference in behavior on IE and Chrome
http://codepen.io/ravindra1103/pen/WRrKmX

**Comment by ido-ran** [comment]
I can also confirm I still see this issue in IE11

**Comment by alansouzati** [comment]
Cool. Let me work on that today.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/34668d9535d42a1a7f4f4cf8a755c32db5915fa4

**Comment by ido-ran** [comment]
Thank you. Any chance of releasing 1.2.1 with this fix please? :1st_place_medal:

**Comment by alansouzati** [comment]
Fair request. Give us a couple of days there are few other issues I would like to include in this new patch release.

**Comment by ericsoderberghp** [comment]
The fix doesn't work in all situations and has made grommet-docs worse. We will need to investigate this further.

**Comment by alansouzati** [comment]
Fixed and tested with other browsers. Grommet 1.2.1 has been released working on the release notes now.

**Comment by ido-ran** [comment]
I can confirm this solve the issue with IE.
Thanks.
