### ISSUE TITLE
Spinner doesn't work in IE 11

### ISSUE THREAD

**Issue by DmitrijDN** [grommet/grommet#1556]
It isn't animated in IE 11

### Expected Behavior

It is animated
### Actual Behavior

it is just a circle
### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/spinning/

### Your Environment

* Grommet version: latest (on your site)
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Windows 10

**Comment by cherih** [comment]
animation-play-state is missing in IE 11.

It works on the latest version of Edge, as well as Chrome.

**Comment by DmitrijDN** [comment]
@cherih In browser support IE11 is presented, so it is necessary to fix or say that IE11 isn't supported

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/pull/1596

**Comment by DmitrijDN** [comment]
@alansouzati Still doesn't work

https://grommet.github.io/docs/spinning

**Comment by karatechops** [comment]
@DmitrijDN the docs have not been updated. I believe [Grommet's latest stable](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) npm package will include the fix.
