### ISSUE TITLE
Inconsistant use of constants "expand" and "explode" in Menu inline prop

### ISSUE THREAD

**Issue by XuluWarrior** [grommet/grommet#1574]
The PropTypes for Menu say that the prop "inline" can either be a bool or the value "expand".
When a Menu is nested in another the inline prop for the child Menu is set to "explode".  This results in a PropTypes warning.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/22ff8308e634829a519010826664ab6cf341a6ab

**Comment by XuluWarrior** [comment]
This is still an issue as the "fix" changed uses of "explode" to "expanded" but PropTypes still expects "expand".  Resulting in a PropTypes warning.
