### ISSUE TITLE
dark theme anchor on brand background

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1984]
The `<Anchor />` is not visible on a `brand` background with the dark theme:
![screenshot689](https://user-images.githubusercontent.com/6075606/37910623-a4d76efc-3116-11e8-89b7-bf0bed10dd01.jpg)
![screenshot688](https://user-images.githubusercontent.com/6075606/37910624-a4f7aeec-3116-11e8-8e92-a3ed62935315.jpg)

**Comment by ericsoderberghp** [comment]
We should fix this for v2.0.0

**Comment by alansouzati** [comment]
I think this should also be fixed with PR https://github.com/grommet/grommet/pull/2131

**Comment by atanasster** [comment]
It was not fixed 
https://grommet-nextjs.herokuapp.com/?theme=dark
