### ISSUE TITLE
v2 Layer - no overlay in small screen

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2271]
https://stackblitz.com/edit/grommet-demo-t3bvxs?file=index.js

Resize the window between narrow and wide and the overlay becomes hidden (no dimming effect and no onClickOutside event).
![screenshot754](https://user-images.githubusercontent.com/6075606/45353060-e612bc00-b587-11e8-95c1-5c5806221ab2.jpg)
![screenshot756](https://user-images.githubusercontent.com/6075606/45353067-e8751600-b587-11e8-8a63-9032102f66db.jpg)

Not sure why the position absolute is removed for narrow size
https://github.com/grommet/grommet/blob/d3003d7627428fbc6ac6022d7928ecdb900f5e4f/src/js/components/Layer/StyledLayer.js#L50

**Comment by atanasster** [comment]
The use case is to make a mobile menu, that will cover partially the screen

**Comment by atanasster** [comment]
Example of desired mobile menu behavior, where the background is partially covered and dimmed.
![screenshot757](https://user-images.githubusercontent.com/6075606/45353213-502b6100-b588-11e8-9ffb-cb1ac8a09f6c.jpg)

**Comment by alansouzati** [comment]
Does responsive false work? You can disable that behavior i believe

**Comment by atanasster** [comment]
Responsive false works fine, and the layer is not full size when set. But the problem is thta the dimmed overlay is not visible

**Comment by alansouzati** [comment]
gotcha!!! yeah this is a bug!

**Comment by prateekgoel** [comment]
Can I work on this? Seems like this is open.

**Comment by spencerkordecki** [comment]
I believe this was fixed by my PR yesterday: https://github.com/grommet/grommet/pull/2315

**Comment by alansouzati** [comment]
yup sorry forgot to close this one!

**Comment by joelachance** [comment]
This is still an issue, unfortunately. Using 'responsive' seems to keep Layer from being scrollable (unsure about the overlay).

**Comment by ShimiSun** [comment]
@joelachance thanks for the input, which version of grommet are you using? Can you confirm it is still reproducible on grommet v2.16.0?

**Comment by joelachance** [comment]
Using 2.15.1 over here, so I can't confirm its on 2.16 :) Thanks for the response!

**Comment by ShimiSun** [comment]
@joelachance thanks, the reason I'm asking is that we added Fixes for Layer on v2.16.0. 
Please give it a try and circle back if you still see the problem, feel free to file a new issue with full details and reproducible code.

**Comment by joelachance** [comment]
I will check it out, thank you!
