### ISSUE TITLE
InfiniteScroll within table throws error: Function components cannot be given refs

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#2636]
When using grommet table components with InfiniteScroll on React 16.7 I get the following error message and subsequent items are not rendered into view:

```
Function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Context.Consumer`.
    in TableRow (created by Context.Consumer)
    …
```

My guess is that due to the missing ref no event listeners are attached and the InfiniteScroll component cannot calculate when new items need to be rendered.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/5vopj41j8n

Relevant code example

```
           <Table>
            <TableBody>
              <InfiniteScroll
                items={entities}
                step={12}
                renderMarker={marker => (
                  <tr>
                    <td>{marker}</td>
                  </tr>
                )}
                onMore={() => console.log("!!! onMore")}
              >
                {(_, ix) => (
                  <TableRow key={`row-${ix}`}>
                    <TableCell key={`cell-${ix}`}>Cell {ix}</TableCell>
                  </TableRow>
                )}
              </InfiniteScroll>
            </TableBody>
          </Table>
```

### Your Environment

- Readt version: 16.7
- Grommet version: 2.2.1
- Browser Name and version: Chrome 71.0.3578.98
- Operating System and version (desktop or mobile): Mac OSX

**Comment by krismorf** [comment]
Hi @florianbepunkt . This was fixed in #2601

**Comment by florianbepunkt** [comment]
Hello @krismorf, has this been pushed to npm yet? I run the latest grommet and the issue in the Codepen still exists.

**Comment by florianbepunkt** [comment]
Okay, I see… the fix just hasn't made it to npm yet. Closing this.
