### ISSUE TITLE
Cursor loses position in TextInput

### ISSUE THREAD

**Issue by csclyde** [grommet/grommet#3702]
### Expected Behavior
When editing text in a TextInput, I enter a string (abc). Then, I move the cursor to the beginning of the string, and start typing (123). My cursor should remain when I put it, giving me "123abc"

### Actual Behavior
When editing text in a TextInput, I enter a string (abc). Then, I move the cursor to the beginning of the string, and start typing (123). After entering one character, my cursor jumps to the end of the input. Giving me "1abc23".

### URL, screen shot, or Codepen exhibiting the issue
The problem is visible in the storybook of the most recent version of Grommet.

**Comment by ShimiSun** [comment]
Thanks for reporting, the fix will be available on our next release.

**Comment by IanKBovard** [comment]
This can be closed. addressed in #3709

**Comment by csclyde** [comment]
@ShimiSun Thanks for the quick work. Will this only be going into Grommet v2, or will it make it into v1 as well? We still have a project using v1. Thanks.

**Comment by ShimiSun** [comment]
Hi @csclyde , thanks for your patience.
Looking at the code for this fix, it is very specific for v2 and wouldn't work on v1, more specifically v1 doesn't use React hooks (react version of ^16.8) so the couldn't apply there.

If you have an idea for a fix on v1, feel free to directly fix it on your local version, we do not have the resources to upgrade and have new releases on v1 at this point, unfortunately.
