### ISSUE TITLE
Form onChange with Controlled Inputs fires multiple times and for programmatic changes

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#3935]
### Expected Behavior

Grommet Form onChange with Controlled Inputs ought to behave the same as it does for Uncontrolled Inputs.  Ideally, these should both behave the same as React form onChange handlers for controlled and uncontrolled inputs.  Specifically:

1) Form onChange only fires for user-input changes to a field within the form
1) Form onChange fires once per change (e.g. fires for each input keystroke)

### Actual Behavior

For Controlled Inputs, the Grommet Form onChange handler fires when:

1) The input changes programmatically or by keyboard input
1) It fires 3 times for each change

As an aside: if the previous value was null, then when it is changed, it fires just once - this is an odd case, since the input would change from uncontrolled to controlled in this case and so generate a warning.).

### URL, screen shot, or Codepen exhibiting the issue

See my CodeSandbox: [form onChange experiments](https://codesandbox.io/s/form-onchange-experiments-6jktb).

### Steps to Reproduce

See CodeSandbox described above.  Here's the basic Form used to illustrate the issue:

            <Form onChange={grommetFormOnChange}>
              <FormField
                id="grommet-controlled-first"
                name="First"
                label="First"
                value={first}
                onChange={firstOnChange}
                component={TextInput}
              />
            </Form>

### Your Environment

- Grommet version: 2.12.0, React 16.12.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ShimiSun** [comment]
Thanks for reporting! This issue is fixed on the [stable branch,](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) feel free to try it out on by pointing your grommet package.json to `"grommet": "https://github.com/grommet/grommet/tarball/stable"` and let us know if it works as expected. 
The fix will be officially available on our next official grommet release.

**Comment by LiveFreeAndRoam** [comment]
I tried to test it, but was unable to.

Would you expect this to work from CodeSandbox?  I tried all manner of variations, but all were unable to locate your tarball.  The error suggests there is a missing `package.json` file in the `grommet/grommet/tarball/stable` folder:

> _Could not fetch https://cdn.jsdelivr.net/gh/grommet/grommet/tarball/stable/package.json_

I modified _my project's_ `package.json` file, replacing the "grommet" dependency with the line you described above, and CodeSandbox reports the following error:

```
Error: Could not fetch https://cdn.jsdelivr.net/gh/grommet/grommet/tarball/stable/package.json
    at https://codesandbox.io/static/js/sandbox.b6beb970f.js:1:205758
```

And for completeness, here is my CodeSandbox.io package.json:

```
{
  "name": "form-onchange-experiments",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "main": "src/index.js",
  "dependencies": {
    "grommet": "https://github.com/grommet/grommet/tarball/stable",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-scripts": "3.4.1",
    "styled-components": "5.1.0"
  },
  "devDependencies": {
    "typescript": "3.3.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": [">0.2%", "not dead", "not ie <= 11", "not op_mini all"]
}
```

**Comment by LiveFreeAndRoam** [comment]
I finally got around to testing this in my own enviornment.  CodeSandbox wouldn't let me reference your stable image.  It's an improvement, but still not quite right.

The Grommet `Form onChange` handler is still invoked for controlled changes to the controlled input.  This is different to the React `Form onChange` handler which does not respond to controlled changes to controlled inputs, but rather only to keyboard inputs.

The code I'm using to validate this is described in my CodeSandbox [App.js](https://codesandbox.io/s/form-onchange-experiments-6jktb?file=/src/App.js:0-7318).  Please take a look so you can easily compare how Grommet Form behaves compared to React Form.

**Comment by LiveFreeAndRoam** [comment]
Notice that entering data into the Grommet Form updates the React Form.  Though the React Form shows Zero changes.

![image](https://user-images.githubusercontent.com/8231064/79328126-e7248000-7f58-11ea-9623-bf606a376704.png)

Repeating the same experiment, entering data into the React Form updates the Grommet Form.  But now the Grommet Form shows it changes for every controlled change.

![image](https://user-images.githubusercontent.com/8231064/79328378-47b3bd00-7f59-11ea-8a75-0ec039b93e00.png)

**Comment by LiveFreeAndRoam** [comment]
This one is getting a little old, so just checking if there are plans to correct it.  We're about to abandon the functionality we had planned on attaching to the Form's onChange event handler.

**Comment by LiveFreeAndRoam** [comment]
I'm not sure if this should be raised as a separate issue.  It's the same problem, just different component.  Feel free to move this if that makes more sense.

In Grommet v2.14, this has been fixed for `TextInput` components, however I just learned that we have the same issue with the `CheckBox` components.

I modified my codeSandbox to add the `CheckBox`.  You can see the way React handles form `onChange`, is different to the way Grommet handles it.

I dare say, other input components might need similar attention.

To observe this behaviour open https://codesandbox.io/s/form-onchange-experiments-6jktb, and toggle the checkbox in each of the panels to observe the difference between React and Grommet.

## Form Controlled CheckBox
After just one click on the Grommet CheckBox, I see: (Grommet onChange fires 3 times, React fires 0 times):

![image](https://user-images.githubusercontent.com/8231064/85804303-a5039000-b78c-11ea-85b4-788f743b1ad8.png)

After just on click on the React CheckBox, I see (Grommet onChange fires 3 times, React fires 1 time per click):

![image](https://user-images.githubusercontent.com/8231064/85804228-78e80f00-b78c-11ea-88a7-7ea67449c140.png)

## Form Uncontrolled CheckBox

The form onChange handler behaves consistently with uncontrolled CheckBox.  The handler is called once for every click.  Here, I have clicked the Grommet CheckBox 3 times and the React CheckBox 5 times.

![image](https://user-images.githubusercontent.com/8231064/85804547-4b4f9580-b78d-11ea-960d-177f76a86587.png)

**Comment by LiveFreeAndRoam** [comment]
I have come across another unfortunate behaviour in Grommet forms that differs from React (I think).  Unfortunately, I have no time to dig into it.

When the browser has autofill data, Grommet's `Form onChange` handler is firing when the form is initially rendered.  I believe this is different to React, where the `form onChange` handler only fires when the user changes a field; i.e. it seems React does not trigger `form onChange` events when form fields are updated by autofill.

The React approach makes sense to me; as it preserves the `form onChange`  handler only for user-initiated changes.

**Comment by bdesouza** [comment]
Spent several hours trying to figure out why I was seeing multiple events for controlled forms and arrived here. I'm still having issues and I'm using 2.16.0.

Any ideas how I can resolve in the short term?

**Comment by LiveFreeAndRoam** [comment]
FYI, the same issue seems to have been reported as #4559.
