### ISSUE TITLE
TextInput suggestion scroll problem

### ISSUE THREAD

**Issue by DrStricker** [grommet/grommet#4098]
When i scroll in the suggestions of a TextInput it won't stop bringin me back to the last suggestion i put my mouse on and i can't really scroll down because of that problem.

### Expected Behavior
A normal scroll down that doesn't bring back at the top of the suggestions or to the last suggestion i hovered

### Actual Behavior
The scroll bar brings me to the top of the suggestions or to the last suggestion i hovered

### URL, screen shot, or Codepen exhibiting the issue

![grommet_problem](https://user-images.githubusercontent.com/41908359/82311543-29ad0280-99c6-11ea-9073-68401c3f355a.gif)

### Steps to Reproduce

1. Create a TextInput and give it a list of suggestions like this one [{label: "label0", value: "value0"}, {label: "label1", value: "value1"}, ...]
 2. Enter a word in the TextInput and scroll in the suggestions
 3. The scroll bring you back to the top of the suggestions or to the last suggestion you hovered

Here is the code that i use : 
<TextInput
    id="text-input"
    placeholder="type here"
    value={value}
    onChange={event => setValue(event.target.value)}
    suggestions={textInputSuggestions}
/>

the textInputSuggestions is formated as said in the first point, value is the word that I enter in the TextInput.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Google Chrome 81.0.4044.138 (official Build) (64 bits)
- Operating System and version (desktop or mobile): Ubuntu 18.04.4 LTS desktop

**Comment by ShimiSun** [comment]
I think this issue is fixed on the stable branch https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F.
Will you be willing to give it a try and let us know whether using the stable (our updated master branch) solved your problem?

**Comment by DrStricker** [comment]
> I think this issue is fixed on the stable branch https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F.
> Will you be willing to give it a try and let us know whether using the stable (our updated master branch) solved your problem?

It works perfectly, thanks !

**Comment by gerson-vfs** [comment]
I have the same issue. But when upgrading to stable version following the above tutorial, the bug still remains.

**Comment by jcfilben** [comment]
HI @gerson-vfs thanks for reporting, I checked and I am seeing this issue again in v2.20.0 of grommet. The issue can be seen in this [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-4c06c?file=/index.js). Note v2.14.0-2.19.1 do not have this issue. (Issue is potentially related to this PR https://github.com/grommet/grommet/pull/5860)

**Comment by gerson-vfs** [comment]
@jcfilben Thanks for your reply. Grommet v2.19.1 worked perfectly.

**Comment by peachy-jonny** [comment]
> @jcfilben Thanks for your reply. Grommet v2.19.1 worked perfectly.

v2.19.1 not worked perfectly.😢

**Comment by jcfilben** [comment]
Hi @peachy-jonny this problem should be fixed on the [stable-branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) could you give that a try?

**Comment by peachy-jonny** [comment]
> Hi @peachy-jonny this problem should be fixed on the [stable-branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) could you give that a try?

Yes, I tried with a stable-branch, but it still doesn't work.
Is there any other way?
