### ISSUE TITLE
Grommet icons page stops loading / hangs

### ISSUE THREAD

**Issue by ronhp** [grommet/grommet#751]
The page stops loading / gets hung while loading the icons.

### Expected Behavior
The icons should automatically keep loading on page scroll.

### Actual Behavior
Page hangs during loading right after the </> code  icon designation.

### URL, screen shot, or Codepen exhibiting the issue
![grommet_iconpage](https://cloud.githubusercontent.com/assets/12156047/17493719/356db658-5d77-11e6-9a41-ec1dd151207b.png)

###  Environment
Page location: http://grommet.github.io/docs/icon/
Chrome browser
Windows 7 Enterprise - desktop

**Comment by alansouzati** [comment]
Thanks for reporting this. Let me check what is going on.

**Comment by alansouzati** [comment]
Fixed.

**Comment by ronhp** [comment]
The problem is still happening in both IE and Chrome.  I am working remotely today, but accessing the network.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-docs/commit/f9476bfae6671784cd23156d15772217088b69f3

Will be soon live.

For the future website issues, please open them in grommet-docs project: https://github.com/grommet/grommet-docs
